In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sns
%matplotlib inline

In [2]:
df_books=pd.read_csv('BX-Books.csv',encoding='latin')

In [3]:
df_books.head()

ISBN                                         Book-Title  \
0  0195153448                                Classical Mythology   
1  0002005018                                       Clara Callan   
2  0060973129                               Decision in Normandy   
3  0374157065  Flu: The Story of the Great Influenza Pandemic...   
4  0393045218                             The Mummies of Urumchi   

            Book-Author  Year-Of-Publication                   Publisher  \
0    Mark P. O. Morford               2002.0     Oxford University Press   
1  Richard Bruce Wright               2001.0       HarperFlamingo Canada   
2          Carlo D'Este               1991.0             HarperPerennial   
3      Gina Bari Kolata               1999.0        Farrar Straus Giroux   
4       E. J. W. Barber               1999.0  W. W. Norton &amp; Company   

                                         Image-URL-S  \
0  http://images.amazon.com/images/P/0195153448.0...   
1  http://images.amazon.com/images/P/0002005018.0...   
2  http://images.amazon.com/images/P/0060973129.0...   
3  http://images.amazon.com/images/P/0374157065.0...   
4  http://images.amazon.com/images/P/0393045218.0...   

                                         Image-URL-M  \
0  http://images.amazon.com/images/P/0195153448.0...   
1  http://images.amazon.com/images/P/0002005018.0...   
2  http://images.amazon.com/images/P/0060973129.0...   
3  http://images.amazon.com/images/P/0374157065.0...   
4  http://images.amazon.com/images/P/0393045218.0...   

                                         Image-URL-L  
0  http://images.amazon.com/images/P/0195153448.0...  
1  http://images.amazon.com/images/P/0002005018.0...  
2  http://images.amazon.com/images/P/0060973129.0...  
3  http://images.amazon.com/images/P/0374157065.0...  
4  http://images.amazon.com/images/P/0393045218.0...

In [4]:
df_books.shape

(271378, 8)

In [5]:
df_books.isnull().sum()

ISBN                       0
Book-Title                 0
Book-Author            37652
Year-Of-Publication    39000
Publisher              39000
Image-URL-S            43264
Image-URL-M            43264
Image-URL-L            43264
dtype: int64

In [6]:
df_books=df_books.dropna(axis=0)

In [7]:
df_books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            0
Year-Of-Publication    0
Publisher              0
Image-URL-S            0
Image-URL-M            0
Image-URL-L            0
dtype: int64

In [8]:
df_ratings=pd.read_csv('BX-Book-Ratings.csv',encoding='latin-1',nrows=10000)

In [9]:
df_ratings.head()

User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726   155061224            5
2   276727   446520802            0
3   276729  052165615X            3
4   276729   521795028            6

In [10]:
df_ratings.shape

(10000, 3)

In [11]:
df_user=pd.read_csv('BX-Users.csv',encoding='latin')
df_user.head()

User-ID                            Location  Age
0      1.0                  nyc, new york, usa  NaN
1      2.0           stockton, california, usa   18
2      3.0     moscow, yukon territory, russia  NaN
3      4.0           porto, v.n.gaia, portugal   17
4      5.0  farnborough, hants, united kingdom  NaN

In [12]:
master_df=pd.merge(df_ratings,df_books,on='ISBN')
master_df.head()

User-ID        ISBN  Book-Rating                   Book-Title  \
0   276725  034545104X            0         Flesh Tones: A Novel   
1   276729  052165615X            3               Help!: Level 1   
2   276733  2080674722            0  Les Particules Elementaires   
3   276744  038550120X            7              A Painted House   
4   278418  038550120X            0              A Painted House   

          Book-Author  Year-Of-Publication                   Publisher  \
0          M. J. Rose               2002.0            Ballantine Books   
1       Philip Prowse               1999.0  Cambridge University Press   
2  Michel Houellebecq               1998.0                  Flammarion   
3        JOHN GRISHAM               2001.0                   Doubleday   
4        JOHN GRISHAM               2001.0                   Doubleday   

                                         Image-URL-S  \
0  http://images.amazon.com/images/P/034545104X.0...   
1  http://images.amazon.com/images/P/052165615X.0...   
2  http://images.amazon.com/images/P/2080674722.0...   
3  http://images.amazon.com/images/P/038550120X.0...   
4  http://images.amazon.com/images/P/038550120X.0...   

                                         Image-URL-M  \
0  http://images.amazon.com/images/P/034545104X.0...   
1  http://images.amazon.com/images/P/052165615X.0...   
2  http://images.amazon.com/images/P/2080674722.0...   
3  http://images.amazon.com/images/P/038550120X.0...   
4  http://images.amazon.com/images/P/038550120X.0...   

                                         Image-URL-L  
0  http://images.amazon.com/images/P/034545104X.0...  
1  http://images.amazon.com/images/P/052165615X.0...  
2  http://images.amazon.com/images/P/2080674722.0...  
3  http://images.amazon.com/images/P/038550120X.0...  
4  http://images.amazon.com/images/P/038550120X.0...

In [13]:
master_df.shape

(1441, 10)

In [14]:
n_users=master_df['User-ID'].nunique()
n_books=master_df.ISBN.nunique()

print('Num of Users: '+str(n_users))
print('Num of Books: '+str(n_books))

Num of Users: 290
Num of Books: 1364


In [15]:
isbn_list=master_df['ISBN'].unique()
isbn_list

array(['034545104X', '052165615X', '2080674722', ..., '3492045642',
       '3499110695', '3548254268'], dtype=object)

In [16]:
print('Length of isbn list:',len(isbn_list))
def get_isbn_numeric_id(isbn):
    itemindex=np.where(isbn_list==isbn)
    return itemindex[0][0]

Length of isbn list: 1364


In [17]:
master_df['ISBN']=master_df['ISBN'].apply(get_isbn_numeric_id)
master_df.head()

User-ID  ISBN  Book-Rating                   Book-Title  \
0   276725     0            0         Flesh Tones: A Novel   
1   276729     1            3               Help!: Level 1   
2   276733     2            0  Les Particules Elementaires   
3   276744     3            7              A Painted House   
4   278418     3            0              A Painted House   

          Book-Author  Year-Of-Publication                   Publisher  \
0          M. J. Rose               2002.0            Ballantine Books   
1       Philip Prowse               1999.0  Cambridge University Press   
2  Michel Houellebecq               1998.0                  Flammarion   
3        JOHN GRISHAM               2001.0                   Doubleday   
4        JOHN GRISHAM               2001.0                   Doubleday   

                                         Image-URL-S  \
0  http://images.amazon.com/images/P/034545104X.0...   
1  http://images.amazon.com/images/P/052165615X.0...   
2  http://images.amazon.com/images/P/2080674722.0...   
3  http://images.amazon.com/images/P/038550120X.0...   
4  http://images.amazon.com/images/P/038550120X.0...   

                                         Image-URL-M  \
0  http://images.amazon.com/images/P/034545104X.0...   
1  http://images.amazon.com/images/P/052165615X.0...   
2  http://images.amazon.com/images/P/2080674722.0...   
3  http://images.amazon.com/images/P/038550120X.0...   
4  http://images.amazon.com/images/P/038550120X.0...   

                                         Image-URL-L  
0  http://images.amazon.com/images/P/034545104X.0...  
1  http://images.amazon.com/images/P/052165615X.0...  
2  http://images.amazon.com/images/P/2080674722.0...  
3  http://images.amazon.com/images/P/038550120X.0...  
4  http://images.amazon.com/images/P/038550120X.0...

In [18]:
user_list=master_df['User-ID'].unique()
print('Length of user_id list:',len(user_list))
def get_user_numeric_id(user):
    itemindex=np.where(user_list==user)
    return itemindex[0][0]

Length of user_id list: 290


In [19]:
master_df['User-ID']=master_df['User-ID'].apply(get_user_numeric_id)
master_df.head()

User-ID  ISBN  Book-Rating                   Book-Title  \
0        0     0            0         Flesh Tones: A Novel   
1        1     1            3               Help!: Level 1   
2        2     2            0  Les Particules Elementaires   
3        3     3            7              A Painted House   
4        4     3            0              A Painted House   

          Book-Author  Year-Of-Publication                   Publisher  \
0          M. J. Rose               2002.0            Ballantine Books   
1       Philip Prowse               1999.0  Cambridge University Press   
2  Michel Houellebecq               1998.0                  Flammarion   
3        JOHN GRISHAM               2001.0                   Doubleday   
4        JOHN GRISHAM               2001.0                   Doubleday   

                                         Image-URL-S  \
0  http://images.amazon.com/images/P/034545104X.0...   
1  http://images.amazon.com/images/P/052165615X.0...   
2  http://images.amazon.com/images/P/2080674722.0...   
3  http://images.amazon.com/images/P/038550120X.0...   
4  http://images.amazon.com/images/P/038550120X.0...   

                                         Image-URL-M  \
0  http://images.amazon.com/images/P/034545104X.0...   
1  http://images.amazon.com/images/P/052165615X.0...   
2  http://images.amazon.com/images/P/2080674722.0...   
3  http://images.amazon.com/images/P/038550120X.0...   
4  http://images.amazon.com/images/P/038550120X.0...   

                                         Image-URL-L  
0  http://images.amazon.com/images/P/034545104X.0...  
1  http://images.amazon.com/images/P/052165615X.0...  
2  http://images.amazon.com/images/P/2080674722.0...  
3  http://images.amazon.com/images/P/038550120X.0...  
4  http://images.amazon.com/images/P/038550120X.0...

In [21]:
from sklearn.model_selection import train_test_split
train_data,test_data=train_test_split(master_df,test_size=0.30)

In [23]:
train_data.itertuples()

In [25]:
train_data_matrix=np.zeros((n_users,n_books))
for line in train_data.itertuples():
    train_data_matrix[line[1]-1,line[2]-1]=line[3]
    
test_data_matrix=np.zeros((n_users,n_books))
for line in test_data.itertuples():
    test_data_matrix[line[1]-1,line[2]-1]=line[3]    

In [26]:
train_data_matrix

array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  7., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ...,  7., 10.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [27]:
test_data_matrix

array([[3., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [28]:
from sklearn.metrics.pairwise import pairwise_distances
user_similarity=pairwise_distances(train_data_matrix,metric='cosine')
item_similarity=pairwise_distances(train_data_matrix.T,metric='cosine')

In [29]:
item_similarity

array([[0., 1., 1., ..., 1., 1., 1.],
       [1., 0., 1., ..., 1., 1., 1.],
       [1., 1., 0., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 0., 0., 1.],
       [1., 1., 1., ..., 0., 0., 1.],
       [1., 1., 1., ..., 1., 1., 0.]])

In [30]:
def predict(ratings,similarity,type='user'):
    if type=='user':
        mean_user_rating=ratings.mean(axis=1)
        ratings_diff=(ratings-mean_user_rating[:,np.newaxis])
        pred=mean_user_rating[:,np.newaxis]+similarity.dot(ratings_diff)/np.array([np.abs(similarity).sum(axis=1)]).T
    elif type=='item':
        pred=ratings.dot(similarity)/np.array([np.abs(similarity).sum(axis=1)])
    return pred

In [31]:
item_prediction=predict(train_data_matrix,item_similarity,type='item')
user_prediction=predict(train_data_matrix,user_similarity,type='user')


In [32]:
item_prediction

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.00513573, 0.00513573, 0.        , ..., 0.00516605, 0.00516605,
        0.00513573],
       ...,
       [0.00660308, 0.00660308, 0.00660308, ..., 0.00664207, 0.00664207,
        0.00660308],
       [0.05796038, 0.05796038, 0.05796038, ..., 0.        , 0.        ,
        0.05796038],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [33]:
user_prediction

array([[-6.54496748e-03, -6.54496748e-03,  1.76764858e-02, ...,
         1.76764858e-02,  2.80571086e-02, -6.54496748e-03],
       [-6.54496748e-03, -6.54496748e-03,  1.76764858e-02, ...,
         1.76764858e-02,  2.80571086e-02, -6.54496748e-03],
       [-1.39524501e-03, -1.39524501e-03, -1.39524501e-03, ...,
         2.28262083e-02,  3.32068311e-02, -1.39524501e-03],
       ...,
       [ 7.61042730e-05,  7.61042730e-05,  2.42975576e-02, ...,
         2.42975576e-02,  3.46781804e-02,  7.61042730e-05],
       [ 5.15733290e-02,  5.15733290e-02,  7.57947823e-02, ...,
         5.15733290e-02,  5.15733290e-02,  5.15733290e-02],
       [-6.54496748e-03, -6.54496748e-03,  1.76764858e-02, ...,
         1.76764858e-02,  2.80571086e-02, -6.54496748e-03]])

In [34]:
from sklearn.metrics import mean_squared_error
from math import sqrt
def rmse(prediction,ground_truth):
    prediction=prediction[ground_truth.nonzero()].flatten()
    ground_truth=ground_truth[ground_truth.nonzero()].flatten()
    return sqrt(mean_squared_error(prediction,ground_truth))

In [35]:
print('User-based CF RMSE: '+str(rmse(user_prediction,test_data_matrix)))
print('Item-based CF RMSE: '+str(rmse(item_prediction,test_data_matrix)))

User-based CF RMSE: 7.613457313166269
Item-based CF RMSE: 7.60809142761007
